import React from "react";
import { Card, CardContent } from "@/components/ui/card";
import { AlertCircle, Printer } from "lucide-react";
import SeverityIndicator from "@/components/ui/severity-indicator";
import NearbyFacilities from "@/components/NearbyFacilities";
import { formatRelativeTime } from "@/lib/utils/format-utils";

interface Instruction {
  id: number;
  title: string;
  description: string;
}

interface Facility {
  id: number;
  name: string;
  distance: string;
  duration: string;
  address: string;
  phone: string;
  openHours: string;
  emergencyServices: boolean;
}

interface AnalysisResult {
  id: number;
  injuryType: string;
  severity: number;
  confidence: number;
  firstAidInstructions: Instruction[];
  recommendedAction: string;
  nearbyFacilities: Facility[];
}

interface ResultsSectionProps {
  analysisResult: AnalysisResult;
  analyzedImage: string;
}

const ResultsSection: React.FC<ResultsSectionProps> = ({ analysisResult, analyzedImage }) => {
  const printInstructions = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    const instructions = analysisResult.firstAidInstructions.map((inst, index) => (
      `<div style="margin-bottom: 1rem">
        <div style="display: flex; align-items: flex-start">
          <div style="background-color: #3182ce; color: white; border-radius: 9999px; width: 1.5rem; height: 1.5rem; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 0.875rem; margin-right: 0.75rem">${index + 1}</div>
          <div>
            <h4 style="font-weight: 500; color: #1a202c; margin-bottom: 0.25rem">${inst.title}</h4>
            <p style="font-size: 0.875rem; color: #4a5568">${inst.description}</p>
          </div>
        </div>
      </div>`
    )).join('');
    
    printWindow.document.write(`
      <html>
        <head>
          <title>First Aid Instructions - ${analysisResult.injuryType}</title>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.5; padding: 2rem; }
            h1, h2, h3 { margin-top: 0; }
            img { max-width: 100%; height: auto; }
            .disclaimer { margin-top: 2rem; font-size: 0.75rem; color: #718096; }
          </style>
        </head>
        <body>
          <h1>First Aid Instructions: ${analysisResult.injuryType}</h1>
          <p><strong>Severity:</strong> ${analysisResult.severity} out of 10</p>
          <p><strong>Recommended Action:</strong> ${analysisResult.recommendedAction}</p>
          
          <h2>First Aid Steps:</h2>
          ${instructions}
          
          <div class="disclaimer">
            <p><strong>IMPORTANT DISCLAIMER:</strong></p>
            <p>This information is provided as general guidance only and is not a substitute for professional medical advice.</p>
            <p>If the condition is severe or life-threatening, please call emergency services (112) immediately.</p>
            <p>Generated by AI First Responder on ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  return (
    <Card className="overflow-hidden">
      {/* Analysis Results */}
      <CardContent className="p-6 border-b border-border">
        <div className="flex justify-between items-start mb-4">
          <h2 className="text-xl font-semibold">Analysis Results</h2>
          <span className="text-sm text-muted-foreground">
            {formatRelativeTime(new Date())}
          </span>
        </div>

        <div className="flex flex-col md:flex-row md:space-x-6">
          <div className="md:w-1/3 mb-4 md:mb-0">
            <img
              className="w-full h-48 object-contain bg-muted rounded-md"
              src={analyzedImage}
              alt="Analyzed injury"
            />
          </div>

          <div className="md:w-2/3">
            <div className="mb-4">
              <div className="flex justify-between mb-1">
                <span className="text-sm font-medium text-foreground/80">Injury Detected</span>
                <span className="text-sm text-muted-foreground">
                  Confidence: {Math.round(analysisResult.confidence * 100)}%
                </span>
              </div>
              <h3 className="text-lg font-bold">{analysisResult.injuryType}</h3>
            </div>

            <SeverityIndicator severity={analysisResult.severity} className="mb-4" />

            <div>
              <div className="flex items-center space-x-2 mb-2">
                <AlertCircle className="h-5 w-5 text-primary" />
                <span className="text-sm font-medium">Recommended Action</span>
              </div>
              <p className="text-sm text-foreground/80">
                {analysisResult.recommendedAction}
              </p>
            </div>
          </div>
        </div>
      </CardContent>

      {/* First Aid Instructions */}
      <CardContent className="p-6 border-b border-border">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-lg font-semibold">First Aid Instructions</h3>
          <button
            onClick={printInstructions}
            className="text-secondary hover:text-secondary/80 text-sm flex items-center"
          >
            <Printer className="h-4 w-4 mr-1" />
            Print
          </button>
        </div>

        <div className="space-y-4">
          {analysisResult.firstAidInstructions.map((instruction, index) => (
            <div key={instruction.id} className="mb-4 last:mb-0">
              <div className="flex items-start">
                <div className="bg-secondary text-white rounded-full w-6 h-6 flex items-center justify-center font-bold text-sm flex-shrink-0 mt-0.5 mr-3">
                  {index + 1}
                </div>
                <div>
                  <h4 className="font-medium text-foreground mb-1">{instruction.title}</h4>
                  <p className="text-sm text-muted-foreground">
                    {instruction.description}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </CardContent>

      {/* Nearby Facilities */}
      <CardContent className="p-6">
        <NearbyFacilities facilities={analysisResult.nearbyFacilities} />
      </CardContent>
    </Card>
  );
};

export default ResultsSection;
